CREATE TABLE buildings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    street VARCHAR(200) NOT NULL,
    street_number VARCHAR(20) NOT NULL,
    neighborhood VARCHAR(100) NOT NULL,
    city_id BIGINT NOT NULL,
    number_of_floors INT NOT NULL,
    FOREIGN KEY (city_id) REFERENCES cities(id)
);

CREATE TABLE floors (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    building_id BIGINT NOT NULL,
    floor_number INT NOT NULL,
    FOREIGN KEY (building_id) REFERENCES buildings(id)
);

CREATE TABLE units (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    floor_id BIGINT NOT NULL,
    unit_number VARCHAR(20) NOT NULL,
    FOREIGN KEY (floor_id) REFERENCES floors(id)
);
