CREATE TABLE neighborhoods (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    city_id BIGINT NOT NULL,
    budget NUMERIC(12, 2) NOT NULL DEFAULT 0,
    coordinator_id BIGINT NOT NULL,
    FOREIGN KEY (city_id) REFERENCES cities(id),
    FOREIGN KEY (coordinator_id) REFERENCES users(id)
);

CREATE TABLE neighborhood_streets (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    neighborhood_id BIGINT NOT NULL,
    street_name VARCHAR(200) NOT NULL,
    start_number INT NOT NULL,
    end_number INT NOT NULL,
    FOREIGN KEY (neighborhood_id) REFERENCES neighborhoods(id) ON DELETE CASCADE
);

