CREATE TYPE request_status AS ENUM ('pending approval', 'approved', 'rejected');

CREATE TABLE building_memberships (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    building_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    unit_number VARCHAR(20) NOT NULL,
    floor_number INT NOT NULL,
    approved_at DATE NOT NULL,
    FOREIGN KEY (building_id) REFERENCES buildings(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE building_access_requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    building_id BIGINT NOT NULL,
    unit_number VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    status request_status NOT NULL DEFAULT 'pending approval',
    rejection_reason VARCHAR(500),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (building_id) REFERENCES buildings(id)
);