CREATE TYPE ad_status AS ENUM ('active', 'archived');
CREATE TYPE ad_type AS ENUM ('offering', 'seeking');
CREATE TYPE ad_category AS ENUM ('moving', 'appliance_repair', 'lending', 'cleaning', 'other');

CREATE TABLE notice_board_ads (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT NOT NULL,
    building_id BIGINT NOT NULL,
    type        ad_type NOT NULL,
    category    ad_category NOT NULL,
    description VARCHAR(1000) NOT NULL,
    date_from   DATE NOT NULL,
    date_to     DATE NOT NULL,
    status      ad_status NOT NULL DEFAULT 'active',
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (building_id) REFERENCES buildings(id)
);

CREATE TABLE notice_board_time_slots (
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ad_id      BIGINT NOT NULL,
    date       DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time   TIME NOT NULL,
    FOREIGN KEY (ad_id) REFERENCES notice_board_ads(id) ON DELETE CASCADE
);

CREATE TABLE notice_board_bookings (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time_slot_id    BIGINT NOT NULL UNIQUE,
    booked_by_ad_id BIGINT NOT NULL,
    FOREIGN KEY (time_slot_id) REFERENCES notice_board_time_slots(id) ON DELETE CASCADE,
    FOREIGN KEY (booked_by_ad_id) REFERENCES notice_board_ads(id) ON DELETE CASCADE
);