CREATE TYPE rental_type AS ENUM ('per_day', 'multi_day');

CREATE TABLE common_rooms (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    floor_number INT NOT NULL,
    rental_type rental_type NOT NULL,
    building_id BIGINT NOT NULL,
    CONSTRAINT fk_building FOREIGN KEY (building_id) REFERENCES buildings(id) ON DELETE CASCADE
);

CREATE TABLE common_room_bookings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    common_room_id BIGINT NOT NULL,
    booked_date DATE NOT NULL,
    CONSTRAINT fk_common_room FOREIGN KEY (common_room_id) REFERENCES common_rooms(id) ON DELETE CASCADE
);