CREATE TYPE common_room_request_status AS ENUM (
    'pending',
    'approved',
    'rejected',
    'pending_date_change'
);

CREATE TABLE common_room_requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    common_room_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    status common_room_request_status NOT NULL DEFAULT 'pending',
    approved_date DATE NULL,
    proposed_date_from DATE NULL,
    proposed_date_to DATE NULL,
    CONSTRAINT fk_common_room FOREIGN KEY (common_room_id) REFERENCES common_rooms(id) ON DELETE CASCADE,
    CONSTRAINT fk_tenant FOREIGN KEY (tenant_id) REFERENCES users(id)
);