CREATE TYPE problem_report_priority AS ENUM ('can wait', 'soon', 'urgent');
CREATE TYPE problem_report_status AS ENUM ('unresolved', 'potentially solved', 'solved');

CREATE TABLE problem_reports (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    building_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    description VARCHAR(1000) NOT NULL,
    priority problem_report_priority NOT NULL,
    reported_at DATE NOT NULL DEFAULT CURRENT_DATE,
    status problem_report_status NOT NULL DEFAULT 'unresolved',
    FOREIGN KEY (building_id) REFERENCES buildings(id),
    FOREIGN KEY (tenant_id) REFERENCES users(id)
);