CREATE TYPE resident_meeting_status AS ENUM ('scheduled', 'confirmed', 'cancelled');

CREATE TABLE resident_meetings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    building_id BIGINT NOT NULL,
    meeting_date DATE NOT NULL,
    meeting_time TIME NOT NULL,
    status resident_meeting_status NOT NULL DEFAULT 'scheduled',
    FOREIGN KEY (building_id) REFERENCES buildings(id)
);

CREATE TABLE resident_meeting_topics (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    meeting_id BIGINT NOT NULL,
    topic VARCHAR(500) NOT NULL,
    FOREIGN KEY (meeting_id) REFERENCES resident_meetings(id) ON DELETE CASCADE
);

CREATE TABLE resident_meeting_attendances (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    meeting_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    unit_number VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (meeting_id) REFERENCES resident_meetings(id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id) REFERENCES users(id),
    CONSTRAINT uq_resident_meeting_unit UNIQUE (meeting_id, unit_number)
);

CREATE TABLE resident_meeting_topic_suggestions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    meeting_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    topic VARCHAR(500) NOT NULL,
    suggested_at TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (meeting_id) REFERENCES resident_meetings(id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id) REFERENCES users(id)
);