CREATE TABLE city_objects (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200) NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE city_object_votes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    city_object_id BIGINT NOT NULL,
    citizen_id BIGINT NOT NULL,
    neighborhood_id BIGINT NOT NULL,
    FOREIGN KEY (city_object_id) REFERENCES city_objects(id) ON DELETE CASCADE,
    FOREIGN KEY (citizen_id) REFERENCES users(id),
    FOREIGN KEY (neighborhood_id) REFERENCES neighborhoods(id) ON DELETE CASCADE,
    UNIQUE (city_object_id, citizen_id, neighborhood_id)
);

CREATE TABLE city_object_reservations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    city_object_id BIGINT NOT NULL,
    neighborhood_id BIGINT NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    FOREIGN KEY (city_object_id) REFERENCES city_objects(id) ON DELETE CASCADE,
    FOREIGN KEY (neighborhood_id) REFERENCES neighborhoods(id) ON DELETE CASCADE
);
