<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunityHub.Application\CommunityHub.Application.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="Images\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Images\NewFolder1\**" />
	  <Content Remove="Images\NewFolder1\**" />
	  <EmbeddedResource Remove="Images\NewFolder1\**" />
	  <None Remove="Images\NewFolder1\**" />
	  <Page Remove="Images\NewFolder1\**" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
	</ItemGroup>

	<ItemGroup>
	  <Page Include="App.xaml" />
	</ItemGroup>

</Project>
