<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunityHub.Application\CommunityHub.Application.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="images\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="images\NewFolder1\**" />
	  <Content Remove="images\NewFolder1\**" />
	  <EmbeddedResource Remove="images\NewFolder1\**" />
	  <None Remove="images\NewFolder1\**" />
	  <Page Remove="images\NewFolder1\**" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="images\neighborhoods\" />
	</ItemGroup>

</Project>
