<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="images\**" />
    <EmbeddedResource Remove="images\**" />
    <None Remove="images\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\communityhubLogo.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\AppLogo\communityhubLogo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="QuestPDF" Version="2026.5.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
