using CommunityHub.Application.DTOs.Reports;
using QuestPDF.Fluent;
using QuestPDF.Helpers;

namespace CommunityHub.Application.Services.Reports;

internal static class ManagerAdsPdfReportHeader
{
    private const string BuildingIconSvg = """
        <svg width="48" height="48" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
            <rect x="6" y="8" width="36" height="36" fill="#FFFFFF"/>
            <rect x="12" y="14" width="6" height="6" fill="#1A2332"/>
            <rect x="22" y="14" width="6" height="6" fill="#1A2332"/>
            <rect x="32" y="14" width="6" height="6" fill="#1A2332"/>
            <rect x="12" y="24" width="6" height="6" fill="#1A2332"/>
            <rect x="22" y="24" width="6" height="6" fill="#1A2332"/>
            <rect x="32" y="24" width="6" height="6" fill="#1A2332"/>
            <rect x="19" y="34" width="10" height="10" fill="#1A2332"/>
        </svg>
        """;

    public static void AddAppBanner(ColumnDescriptor column, ManagerAdsReportDto report)
    {
        column.Item()
            .Background(ManagerAdsPdfReportStyles.Primary)
            .Padding(14)
            .Row(row =>
            {
                AddBuildingIcon(row);
                AddApplicationInfo(row);
                AddManagerInfo(row, report.ManagerName);
            });
    }

    public static void AddReportHeader(ColumnDescriptor column, ManagerAdsReportDto report)
    {
        column.Item()
            .Background(ManagerAdsPdfReportStyles.Surface)
            .Border(1)
            .BorderColor(ManagerAdsPdfReportStyles.Border)
            .Padding(16)
            .Column(header =>
            {
                header.Item().Text("Notice Board Status Report")
                    .FontSize(20)
                    .Bold()
                    .FontColor(ManagerAdsPdfReportStyles.Primary);

                header.Item().PaddingTop(4)
                    .Text($"Building: {report.BuildingSubtitle}")
                    .FontSize(12)
                    .FontColor(ManagerAdsPdfReportStyles.TextSecondary);

                header.Item().PaddingTop(2)
                    .Text($"Showing: currently active ads - {ManagerAdsPdfReportFormatter.FormatType(report.Type)}")
                    .FontSize(12)
                    .FontColor(ManagerAdsPdfReportStyles.TextSecondary);
            });
    }

    private static void AddBuildingIcon(RowDescriptor row)
    {
        row.ConstantItem(48).Height(48).AlignMiddle().Svg(BuildingIconSvg);
    }

    private static void AddApplicationInfo(RowDescriptor row)
    {
        row.RelativeItem().PaddingLeft(14).Column(left =>
        {
            left.Item().Text("CommunityHub")
                .FontSize(18)
                .Bold()
                .FontColor(Colors.White);

            left.Item().PaddingTop(2)
                .Text("Building Manager Portal")
                .FontSize(9)
                .FontColor(ManagerAdsPdfReportStyles.PrimarySoft);
        });
    }

    private static void AddManagerInfo(RowDescriptor row, string managerName)
    {
        row.ConstantItem(160).AlignRight().Column(right =>
        {
            right.Item().AlignRight()
                .Text("Generated by")
                .FontSize(8)
                .FontColor(ManagerAdsPdfReportStyles.PrimarySoft);

            right.Item().AlignRight()
                .Text(managerName)
                .FontSize(13)
                .Bold()
                .FontColor(Colors.White);
        });
    }
}